[server]
enableCORS = false
enableXsrfProtection = false
headless = true

[theme]
base = "dark"
primaryColor = "#22c55e"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0f172a"
textColor = "#e5e7eb"

[browser]
gatherUsageStats = false
